server:
  port: 11622

spring:
  application:
    name: Hakihive

  ai:
    openai:
      api-key: sk-xxxx   # You configure
      base-url: https://api.openai.com

hakihive:
  models:
    # Models config properties,see org/hakizumi/hakihive/config/ModelProperties
    decision-model: gpt-4  # main reply model

  tools:
    # config about ai-agent-tools
    system-tools:
      enable: true

    io-tools:
      enable: true
      # see org.hakizumi.hakihive.tools.IOTools
      whitelist:
        - E:/safe_path    # Safe path
      blacklist:
        # blacklist paths ( model cannot access )
        - /    # All

      # If the whitelist and blacklist have duplicated entries, an IllegalArgumentException will be called

logging:
  level:
    root: info
    org.hakizumi.hakihive: debug